import { NextRequest, NextResponse } from "next/server";
import { supabase } from "@/lib/supabase";
import { attachFeedbackDocToSubmission } from "@/lib/classroom";

export async function POST(req: NextRequest) {
  try {
    const authHeader = req.headers.get("authorization");
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      return NextResponse.json({ error: "Missing Google Classroom token" }, { status: 401 });
    }
    const token = authHeader.split(" ")[1];

    const { assignmentId } = await req.json();
    if (!assignmentId) {
      return NextResponse.json({ error: "Missing assignmentId" }, { status: 400 });
    }

    // Fetch assignment details
    const { data: assignment, error: assignmentError } = await supabase
      .from("assignments")
      .select("*")
      .eq("id", assignmentId)
      .single();

    if (assignmentError || !assignment) throw new Error("Assignment not found");

    if (!assignment.gc_course_id || !assignment.gc_coursework_id) {
       return NextResponse.json({ error: "Not a Google Classroom assignment" }, { status: 400 });
    }

    // Fetch all graded submissions from DB
    const { data: submissions, error: submissionsError } = await supabase
      .from("submissions")
      .select("*")
      .eq("assignment_id", assignmentId)
      .eq("status", "graded");

    if (submissionsError || !submissions) throw new Error("Could not fetch submissions");

    if (submissions.length === 0) {
      console.log(`[post-feedback-doc] Found 0 graded submissions for assignment ${assignmentId}`);
      return NextResponse.json({ 
        success: true, 
        count: 0, 
        debug: { skippedReasons: ["0 graded submissions found in database for this assignment"] } 
      });
    }
    
    console.log(`[post-feedback-doc] Found ${submissions.length} graded submissions`);

    // Check which submissions already have feedback generated by checking GC Submissions API
    const gcSubsRes = await fetch(
      `https://classroom.googleapis.com/v1/courses/${assignment.gc_course_id}/courseWork/${assignment.gc_coursework_id}/studentSubmissions`,
      { headers: { Authorization: `Bearer ${token}` } }
    );
    const gcSubsData = await gcSubsRes.json();
    const gcSubmissions = gcSubsData.studentSubmissions || [];

    // Map GC submissions to see if they have the TitanGrade feedback doc attached
    const existingFeedbackDocs = new Map<string, string>(); // submissionId -> documentId
    gcSubmissions.forEach((sub: any) => {
      if (sub.assignmentSubmission && sub.assignmentSubmission.attachments) {
        const feedbackAttachment = sub.assignmentSubmission.attachments.find(
          (a: any) => a.driveFile && a.driveFile.title?.startsWith("TitanGrade Feedback:")
        );
        if (feedbackAttachment) {
          existingFeedbackDocs.set(sub.id, feedbackAttachment.driveFile.id);
        }
      }
    });

    console.log(`[post-feedback-doc] existingFeedbackDocs =`, Array.from(existingFeedbackDocs.keys()));

    let count = 0;
    const debugInfo: any = {
      totalGradedFromDb: submissions.length,
      existingDocsFound: existingFeedbackDocs.size,
      existingDocIds: Array.from(existingFeedbackDocs.values()),
      skippedReasons: []
    };
    // Iterate over our graded submissions
    for (const sub of submissions) {
      console.log(`[post-feedback-doc] Checking sub ${sub.id} (gc_id: ${sub.gc_submission_id})`);
      if (!sub.gc_submission_id) {
        debugInfo.skippedReasons.push(`${sub.student_name}: no gc_submission_id`);
        continue;
      }
      
      const existingDocId = existingFeedbackDocs.get(sub.gc_submission_id);

      if (!sub.feedback) {
        debugInfo.skippedReasons.push(`${sub.student_name}: no feedback text`);
        continue;
      }

      try {
        await attachFeedbackDocToSubmission(
          assignment.gc_course_id,
          assignment.gc_coursework_id,
          sub.gc_submission_id,
          sub.student_name,
          sub.feedback,
          token,
          existingDocId
        );
        count++;
      } catch (attachErr: any) {
        console.error(`Failed to attach feedback doc for ${sub.student_name}:`, attachErr);
        debugInfo.skippedReasons.push(`${sub.student_name}: Attachment failed - ${attachErr.message}`);
      }
    }

    return NextResponse.json({ success: true, count, debug: debugInfo });
  } catch (error: any) {
    console.error("Manual Feedback Release Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
